### ISSUE TITLE
Reproducing results in paper

### ISSUE THREAD

**Issue by pdejorge** [yyliu01/RPL#9]
Dear authors,

Congratulations on this very interesting work!

I have run the code in `rpl_corocl.code/main.py` without modifying the `config.py` (except for dset paths), however, I obtained different results from the ones reported in the main paper.

e.g. we obtain:
```
Fishyscapes_ls_auprc
0.640490225812078
Fishyscapes_ls_auroc
0.9911692788663368
```

While in the wandb [report](https://wandb.ai/yy/RPL?workspace=user-pyedog1976) it is reported:
```
Fishyscapes_ls_auprc
0.731714887133006
Fishyscapes_ls_auroc
0.9925962388555352
```

In fact this is more than  stated in the paper Table 1:
```
Fishyscapes_ls_auprc
70.61
Fishyscapes_ls_auroc
99.39
```

I also noticed that the number of epochs in the wandb report is set to 80 while in the `config.py` in the repo right now is set to 40.

Should I simply set the number of epochs to 80 to get the same results? Are there any other configs I should modify?

Thank you in advance,
Pau

**Comment by yyliu01** [comment]
Hi @pdejorge 

The reproduced results might be slightly different, but anyway, could you please share your wandb report?

I want to see more details, like our training log in here:
https://wandb.ai/yy/RPL/runs/3wh3o12o/logs?workspace=user-pyedog1976

Cheers,
Yuyuan

**Comment by pdejorge** [comment]
Hi Yuyuan,

Thank for the quick response. Here's the log:
https://wandb.ai/pdejorge/OoD_Segmentation/runs/3ag308me/overview?workspace=user-pdejorge

Regards,
Pau

**Comment by yyliu01** [comment]
Hi @pdejorge 

I can't find the reason from the report, while the difference between our wandb results and the paper is because we tried to find the best results across all the benchmarks with **_unique_** checkpoint. You can observe the same results in ``iteration 9768`` of our provided training log in [here](https://drive.google.com/drive/folders/1Ba3IpT4CY5hxvGkvBfHLNIcD89Ml8Hmm) and also the related checkpoints.

The potential issue is because of the [different package versions](https://github.com/yyliu01/RPL/blob/main/docs/installation.md), please install our dependencies via
```
$ conda env create -f rpl.yml
```
. Increasing the number of training epochs may not lead to significant differences, and I apologize that I can't assist further in reproducing the results.

Cheers,
Yuyuan

**Comment by pdejorge** [comment]
Hi Yuyuan,

In fact, I installed the conda environment as suggested so I would expect all the packages to be the same. I am using an NVIDIA A100 instead of A40 but I would not expect this to cause such a difference in behaviour. In any case, thank you for your efforts.

Regards,
Pau
